### ISSUE TITLE
hello,canwe talk about this project?

### ISSUE THREAD

**Issue by xiaoxiamiyi** [wutailong0725/SolarTower#1]
https://github.com/wutailong0725/SolarTower/blame/5e6283f36d5e9d48c427c55665af790cce3c1152/code/MainObject.cs#L6

**Comment by xiaoxiamiyi** [comment]
xiaxiamiyi@gmail.com
This is my email,thx~

**Comment by tailong-wu** [comment]
Sure，what do you want to talk about this project？
I tried to reply to you at the email address you provided but failed.
please make sure the email address is correct.
i will keep this comment

**Comment by xiaoxiamiyi** [comment]
thx for your answering~
哥，你好，搜索看您是温州大学的学生，然后在github上检索到您对塔式太阳能镜场的发展有一些研究。
但是没有继续下去，想问下您是这个方向的老师或者是研究生吗；
我现在研二，课题也是这个方向，想交流下想法，可以更好开展课题研究

Tailong_Wu_0725 ***@***.***> 于2023年10月15日周日 00:46写道：

**Comment by tailong-wu** [comment]
你好，我现在是温州大学的本科生，这个项目是由我个人在温州大学何才透教授带领下开发的一项镜场能量的仿真可视化软件，主要功能是镜场的三维可视化和相关定义情况下集热塔上的总能量的计算，如何希望进一步交流可以加我QQ2512421873。
